### ISSUE TITLE
Make buildable with JDK8

### ISSUE THREAD

**Issue by bertfrees** [joeha480/dotify#136]
- [ ] Fix Javadoc issues

**Comment by bertfrees** [comment]
The can keep targeting JRE 7, but it would be great the build would work with JDK8. I can easily use 7 but @dkager is tied to 8 at Dedicon.

**Comment by joeha480** [comment]
Until we target Java 8, I am not going to deal with java 8 issues. If this is a requirement we should put it in the next sprint. You need to upgrade as well then, right?

**Comment by dkager** [comment]
Java 7 is end-of-life. You have to look hard to find it compared to Java 8. IMO the philosophy should be to support as many older platforms as possible while making the thing build on whatever the platform vendor considers the current version.

Let's discuss the more general issue of documentation and platform support for the next sprint. I'm fine with anything, though having to run both Java 7 and Java 8 to build the whole system including web UI really bugs me. We should definitely decide on a common strategy, either support current platforms or only support whatever we're targeting. But then again, the doclint errors are legitimate, even though they should probably have been warnings, and the fix is trivial and takes less time than this very discussion.

**Comment by bertfrees** [comment]
OK let's do it next sprint. I agree with Davy that these Javadoc errors make sense. Also in Java 7 the generated Javadocs are wrong. A few also generate warnings with JDK7 by the way.

**Comment by bertfrees** [comment]
Yes I need to upgrade too then: see https://github.com/daisy/pipeline-mod-braille/issues/59

**Comment by joeha480** [comment]
1. First of all, Java 7 is not end of life, that's just not true, see https://spring.io/blog/2015/04/01/ongoing-support-for-java-7-and-even-java-6
1. Having multiple JDKs is part of everyday java development, if your IT-department refuses to accomodate you, then Dedicon really shouldn't do java development.
1. Further, I don't understand why you can't use JDK 7 anyway. All it takes is to put the files in a folder and point to it from the IDE. I am sure we can get you a copy of the files, if you can't run the installer.
1. I am not against Java 8, but I just moved my code from JDK 6 a few days ago in an attempt to make you happier, but I would like to do the upgrade properly and update the code before moving on to the next version.
1. We JUST finished the sprint planning, and throwing this in now is just madness, especially considering we've never made a decision to leave Java 7 and considering I have to deliver a big rewrite in two-three days time (which is barely possible, by the way).
1. We should realize that our "system" is made up of individual parts that may have priorities and timetables of their own that we cannot control (I guess that could explain why the GUI suddenly requires Java 8).
1. I doubt that moving to Java 8 is more important to everyone than getting actual features in, such as tables.

If you want to make changes to the code or javadoc, go ahead, but you'll have to verify that it works under the JVM that is currently the target. And if changes made later break your (unsupported) version, you'll have to fix that too. If there is a problem with the code or the javadoc that you have fixed, then I have no reason to argue as long as you don't mention Java 8.
